DROP TABLE vote IF EXISTS;
DROP TABLE menus_menuitems_link IF EXISTS;
DROP TABLE menuitem IF EXISTS;
DROP TABLE menus IF EXISTS;
DROP TABLE restaurant IF EXISTS;
DROP TABLE user_role IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name       VARCHAR(255)            NOT NULL,
    email      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL,
    enabled    BOOLEAN   DEFAULT TRUE  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
    ON USERS (email);

CREATE TABLE user_role
(
    user_id INTEGER      NOT NULL,
    role    VARCHAR(255) NOT NULL,
    enabled          BOOLEAN   DEFAULT TRUE  NOT NULL,
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE restaurant
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT restaurant_name_idx UNIQUE (name)
);

CREATE TABLE vote
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    vote_date     DATE DEFAULT now() NOT NULL,
    user_id       INTEGER            NOT NULL,
    restaurant_id INTEGER            NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)
);
CREATE UNIQUE INDEX vote_unique_date_user_idx
    ON vote (vote_date, user_id);

CREATE TABLE menus
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    menu_date     DATE DEFAULT now() NOT NULL,
    restaurant_id INTEGER            NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)
);

CREATE TABLE menuitem
(
    id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name  VARCHAR(255)      NOT NULL,
    price FLOAT DEFAULT 500 NOT NULL,
    CONSTRAINT menuitem_idx UNIQUE (name)
);

CREATE TABLE menus_menuitems_link
(
    menu_id     INTEGER NOT NULL,
    menuitem_id INTEGER NOT NULL,
    PRIMARY KEY (menu_id, menuitem_id),
    FOREIGN KEY (menu_id) REFERENCES menus (id),
    FOREIGN KEY (menuitem_id) REFERENCES menuitem (id)
);




