DROP TABLE restaurant IF EXISTS;
DROP TABLE menu IF EXISTS;
DROP TABLE menuitem IF EXISTS;
DROP TABLE menu_menuitem IF EXISTS;
DROP TABLE menu_history IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE restaurant
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE menu
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant_id INTEGER           NOT NULL,
    date_time     TIMESTAMP DEFAULT now() NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

CREATE TABLE menuitem
(
    id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name  VARCHAR(255)      NOT NULL,
    price FLOAT DEFAULT 500 NOT NULL,
    CONSTRAINT menuitem_idx UNIQUE (name)
);

CREATE TABLE menu_menuitem
(
    menu_id     INTEGER NOT NULL,
    menuitem_id INTEGER NOT NULL,
    PRIMARY KEY (menu_id, menuitem_id),
    FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE,
    FOREIGN KEY (menuitem_id) REFERENCES menuitem (id) ON DELETE CASCADE
);

create TABLE menu_history
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date_time     TIMESTAMP DEFAULT now() NOT NULL,
    restaurant_id INTEGER                 NOT NULL,
    menu_id       INTEGER                 NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    FOREIGN KEY (menu_id) REFERENCES menu (id)
);



