spring:
  jpa:
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: true
  datasource:
    # ImMemory
    url: jdbc:h2:mem:dlv
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:dlv
    # Absolute path
    #    url: jdbc:h2:C:/projects/dlv/db/dlv
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/dlv/db/dlv
    # Relative path form current dir
    #    url: jdbc:h2:./db/dlv
    # Relative path from home
    #    url: jdbc:h2:~/dlv
    #    tcp: jdbc:h2:tcp://localhost:9092/~/dlv
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  cache:
    type: simple

logging:
  level:
    root: WARN
    ru.javapractice.dailylunchvoting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.springframework.test.context.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: TRACE
    org.hibernate.engine.jdbc.batch.internal.BatchImpl: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    com.github.benmanes.caffeine.cache: DEBUG
    org.springframework.cache.interceptor.CacheInterceptor: DEBUG
    org.springframework.cache.caffeine.CaffeineCache: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

springdoc.swagger-ui.path: /